language: python
dist: trusty
env:
  matrix:
    - PYTHON_VERSION=2.7
    - PYTHON_VERSION=3.6
    - PYTHON_VERSION=3.7
services:
  - postgres
before_install:
    - wget -q https://repo.anaconda.com/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh
    - chmod +x miniconda.sh
    - ./miniconda.sh -b -p /home/travis/miniconda
    - export PATH=/home/travis/miniconda/bin:$PATH
    - conda update --yes --quiet conda
install:
    - conda create --yes -n testenv python=$PYTHON_VERSION
    - conda env update -n testenv -f environment.yml
    - conda env create -f ci_tools/environment_iris_kit.yml
    - source activate testenv
    - make install
script:
    - bash ci_tools/travis/test_ramp_frontend.sh
    - bash ci_tools/travis/test_ramp_engine.sh
    - bash ci_tools/travis/test_ramp_database.sh
    - bash ci_tools/travis/test_ramp_utils.sh
after_success:
    - make code-analysis
notifications:
  email: true
